TheLiquidBay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/',include('user.urls')),
    path('store/',include('store.urls')),

    # path('password-reset/',auth_views.PasswordResetView.as_view(template_name='main/password_reset.html'),name='password_reset'),
    # path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),name='password_reset_confirm'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
	path('', views.home, name='home'),
	path('about/', views.about, name='about'),

]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
	path('front/',views.store_front,name='store_front'),
	
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView

app_name = 'user'

urlpatterns = [
	path('register/',views.register,name='register'),
	path('login/',LoginView.as_view(template_name='user/login.html'),name='login'),
	path('logout/',LogoutView.as_view(template_name='user/logout.html'),name='logout'),
	path('profile/',views.profile,name='profile'),
	path('profil-edit/',views.profile_edit,name='profile_edit'),
	# path('password-reset/',PasswordResetView.as_view(template_name='user/password_reset.html'),name='password_reset'),
	# path('password-reset/done/',PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),
	# path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),name='password_reset_confirm'),
]

main/models.py
from django.db import models

# Create your models here.


store/models.py
from django.db import models

# Create your models here.

class Liquid(models.Model):
	name = models.CharField(max_length=100)
	contents = models.TextField()
	image = models.ImageField(default='default_liquid.jpg',upload_to='liquid_pics')

	def __str__(self):
		return self.name

user/models.py
from django.db import models
from django.contrib.auth.models import User
from .choices import *
from PIL import Image

# Create your models here.

class Profile(models.Model):

	user = models.OneToOneField(User, on_delete=models.CASCADE)
	image = models.ImageField(default='default_profile.jpg',upload_to='profile_pics')
	city = models.CharField(max_length=2, choices=CITY, default=CAIRO)
	adress = models.TextField(default="")


	def __str__(self):
		return f'{self.user.username} Profile'

	def save(self):
		super().save()

		img = Image.open(self.image.path)

		if img.height > 300 or img.width > 300:
			output_size = (300,300)
			img.thumbnail(output_size)
			img.save(self.image.path)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from .choices import *

class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username','email','password1','password2']



class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
	city = forms.ChoiceField(choices=CITY,)
	adress = forms.CharField(max_length=200)

	class Meta:
		model = Profile
		fields = ['city','adress','image']

main/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
	context = {
	'title':'Home'
	}
	return render(request, 'main/home.html',context)

def about(request):
	context = {
	'title':'About'
	}
	return render(request,'main/about.html',context)

store/views.py
from django.shortcuts import render
from .models import Liquid

# Create your views here.

def store_front(request):
	context = {
	'title':'Store',
	'store': True,
	'liquids': Liquid.objects.all()
	}
	return render(request,'store/front.html',context)

user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Account created successfully for : {username}')
			login(request, user)
			return redirect('main:home')
		else:
			for msg in form.error_messages:
				messages.error(request, f"{form.error_messages[msg]}")
			
	else:
		form = UserRegisterForm()
	context = {
	'title':'Register',
	'form':form
	}
	return render(request,'user/register.html',context)


@login_required
def profile(request):
	context = {
	'title':'Profile'
	}

	return render(request, 'user/profile.html',context)

@login_required
def profile_edit(request):
	if request.method == 'POST':
		u_form = UserUpdateForm(request.POST, instance=request.user)
		p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request, f"Successfully updated Profile")
			return redirect('user:profile')

	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.profile)

	context = {
	'u_form': u_form ,
	'p_form': p_form
	}

	return render(request, 'user/profile_edit.html',context)


# def password_reset_done(request):
# 	return render(request, 'user/password_reset_done.html')

main/templates/main/about.html
{% extends "main/base.html" %}
{% block content %}

	<h2>About page</h2>

{% endblock content %}

main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
	{% include "main/includes/header.html" %}
</head>

<body class="grey lighten-2">
	{% include "main/includes/nav.html" %}
	<div class="container">

		{% if store %}

		{%  else %}

		<div class="col s12 m8 offset-m2 l6 offset-l3">
  			<div class="card-panel grey lighten-5 z-depth-1 hoverable">
    			<div class="row">

    	{% endif %}

					{% block content %}
						<h2>Are you lost ?</h2>
						<h3>head home <a href="{% url 'home-page' %}"></a></h3>
					{% endblock content %}
				</div>
			</div>
		</div>
	</div>



    <script>
	    $(document).ready(function(){
	    $('.sidenav').sidenav();
		});
    </script>

</body>

{% include "main/includes/footer.html" %}

</html>

main/templates/main/home.html
{% extends "main/base.html" %}

{% block content %}

	<h2>Welcome home</h2>

{% endblock content %}

main/templates/main/includes/footer.html
<!-- till we use sticky footer

<footer class="page-footer blue-grey darken-3">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2019 Copyright TheLiquidBay
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

-->

main/templates/main/includes/header.html
	<!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<!-- Compiled and minified CSS--> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Let browser know website is optimized for mobile-->
 	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

 		<!--Import jQuery before materialize.js-->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


    {% if title %}
		<title> TLB - {{ title }} </title>
	{% else %}
		<title> TheLiquidBay </title>
	{% endif %}

main/templates/main/includes/nav.html
{% if user.is_authenticated %}

  <nav>
    <div class="nav-wrapper blue-grey darken-3">
      <div class="container">
        <a href="{% url 'main:home' %}" class="brand-logo">TheLiquidBay</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i>
        </a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'store:store_front' %}">Store</a></li>
          <li><a href="{% url 'user:profile' %}">Profile</a></li>
          <li><a href="{% url 'user:logout' %}">Logout</a></li>
        </ul>
      </div>
    </div>                 
  </nav>

  {% if messages %}
    {% for message in messages %}
      {% if message.tags == 'success'%}
        <script>M.toast({html: "{{message}}", classes: 'light-green darken-4', displayLength:4000});</script>
      {% elif message.tags == 'info'%}
        <script>M.toast({html: "{{message}}", classes: 'light-blue darken-4', displayLength:4000});</script>
      {% elif message.tags == 'warning'%}
          <script>M.toast({html: "{{message}}", classes: 'amber darken-4', displayLength:10000});</script>
      {% elif message.tags == 'error'%}
          <script>M.toast({html: "{{message}}", classes: 'red darken-4', displayLength:10000});</script>
      {% endif %}
    {% endfor %}
  {% endif %}

  <ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'store:store_front' %}">Store</a></li>
    <li><a href="{% url 'user:profile' %}">Profile</a></li>
    <li><a href="{% url 'user:logout' %}">Logout</a></li>
  </ul>

{% else %}

  <nav>
    <div class="nav-wrapper blue-grey darken-3">
      <div class="container">
        <a href="{% url 'main:home' %}" class="brand-logo">TheLiquidBay</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i>
        </a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'store:store_front' %}">Store</a></li>
          <li><a href="{% url 'user:register' %}">register</a></li>
          <li><a href="{% url 'user:login' %}">Login</a></li>
        </ul>
      </div>
    </div>                 
  </nav>
  
  {% if messages %}
    {% for message in messages %}
      {% if message.tags == 'success'%}
        <script>M.toast({html: "{{message}}", classes: 'light-green darken-4', displayLength:4000});</script>
      {% elif message.tags == 'info'%}
        <script>M.toast({html: "{{message}}", classes: 'light-blue darken-4', displayLength:4000});</script>
      {% elif message.tags == 'warning'%}
          <script>M.toast({html: "{{message}}", classes: 'amber darken-4', displayLength:10000});</script>
      {% elif message.tags == 'error'%}
          <script>M.toast({html: "{{message}}", classes: 'red darken-4', displayLength:10000});</script>
      {% endif %}
    {% endfor %}
  {% endif %}

  <ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'store:store_front' %}">Store</a></li>
    <li><a href="{% url 'user:register' %}">register</a></li>
    <li><a href="{% url 'user:login' %}">Login</a></li>
  </ul>

{% endif %}

main/templates/main/password_reset.html
{% extends "main/base.html" %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	<legend>Reset Password</legend>
	{{  form.as_p }}
	<button class="btn waves-effect blue-grey darken-3" type="submit">request password</button>	
</form>
{% endblock content %}

store/templates/store/front.html
{% extends "main/base.html" %}

{% block content %}

	<h2>Top Picks</h2>

	{% for liquid in liquids %}

		<div class="row">
		    <div class="col s12 m7">
		      <div class="card hoverable">
		        <div class="card-image">
		          <img src="{{ liquid.image.url }}">
		          <span class="card-title">{{ liquid.name }}</span>
		        </div>
		        <div class="card-content">
		          <p>{{ liquid.contents }}</p>
		        </div>
		        <div class="card-action">
		          <a href="#">Details</a>
		        </div>
		      </div>
		    </div>
		  </div>

	{% endfor %}

{% endblock content %}

user/templates/user/login.html
{% extends "main/base.html" %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	<legend>Log in</legend>
	{{  form.as_p }}
	<button class="btn waves-effect blue-grey darken-3" type="submit">Sign In</button>
</form>
<small>
	Need an account? <a href="{% url 'user:register' %}">Sign Up now</a> 
</small>
{% endblock content %}

user/templates/user/logout.html
{% extends "main/base.html" %}
{% block content %}
<h2>You have loged out</h2>
<small>
	Want to <a href="{% url 'user:login' %}">Login</a> again ? 
</small>
{% endblock content %}

user/templates/user/password_reset.html
{% extends "main/base.html" %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	<legend>Reset Password</legend>
	{{  form.as_p }}
	<button class="btn waves-effect blue-grey darken-3" type="submit">request password</button>	
</form>
{% endblock content %}

user/templates/user/password_reset_confirm.html
{% extends "main/base.html" %}
{% block content %}
<form method="POST">
	{% csrf_token %}
	<legend>Reset Password</legend>
	{{  form.as_p }}
	<button class="btn waves-effect blue-grey darken-3" type="submit">reset password</button>	
</form>
{% endblock content %}

user/templates/user/password_reset_done.html
{% extends "main/base.html" %}
{% block content %}

	<h6>Email sent, check your inbox for the instructional email.</h6>
	<script>M.toast({html: "Check your Email", classes: 'light-blue darken-4', displayLength:4000});</script>

{% endblock content %}

user/templates/user/profile.html
{% extends "main/base.html" %}
{% block content %}

<div class="row s10">
  <div class="col s2 hide-on-med-and-down">
    <img src="{{ user.profile.image.url }}" alt="" class="circle responsive-img">
  </div>
  <h3>
    {{ user.username }}
  </h3>
  <span>
    {{ user.email }}
  </span>
  <div class="row">
    <div class="col s10 offset-s10">
        <a href="{% url 'user:profile_edit' %}" class="btn waves-effect blue-grey darken-3 ">
          update
        </a>       
    </div>
  </div>
</div>
{% endblock content %}

<!-- valign-wrapper  -->

user/templates/user/profile_edit.html
{% extends "main/base.html" %}
{% block content %}
<div class="row">
	<div class="col s2 hide-on-med-and-down">
	  <img src="{{ user.profile.image.url }}" alt="" class="circle responsive-img">
	</div>
</div>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <legend>Profile</legend>
      {{  u_form.as_p }}
      {{  p_form.as_p }}
  <button class="btn waves-effect blue-grey darken-3" type="submit">Update</button>
</form>
{% endblock content %}

user/templates/user/register.html
{% extends "main/base.html" %}
{% block content %}
<form method="POST">
		{% csrf_token %}
		<legend>Join Today</legend>
	{{  form.as_p }}
	<button class="btn waves-effect blue-grey darken-3" type="submit">Sign Up</button>
</form>
<small>
	Already have an account? <a href="{% url 'user:login' %}">Sign In</a> 
</small>
{% endblock content %}